export const GET_USER_WALLET = "GET_USER_WALLET"
export const GET_USER_WALLET_SUCCESS = "GET_USER_WALLET_SUCCESS"
export const GET_USER_WALLET_FAILURE = "GET_USER_WALLET_FAILURE"

export const GET_WALLET_TXNS = "GET_WALLET_TXNS"
export const GET_WALLET_TXNS_SUCCESS = "GET_WALLET_TXNS_SUCCESS"
export const GET_WALLET_TXNS_FAILURE = "GET_WALLET_TXNS_FAILURE"

export const DEPOSIT_MONEY = "DEPOSIT_MONEY"
export const DEPOSIT_MONEY_SUCCESS = "DEPOSIT_MONEY_SUCCESS"
export const DEPOSIT_MONEY_FAILURE = "DEPOSIT_MONEY_FAILURE"