export const FETCH_COIN_LIST = "FETCH_COIN_LIST"
export const FETCH_COIN_LIST_SUCCESS = "FETCH_COIN_LIST_SUCCESS"
export const FETCH_COIN_LIST_FAILURE = "FETCH_COIN_LIST_FAILURE"

export const FETCH_TOP_50_COINS = "FETCH_TOP_50_COINS"
export const FETCH_TOP_50_COINS_SUCCESS = "FETCH_TOP_50_COINS_SUCCESS"
export const FETCH_TOP_50_COINS_FAILURE = "FETCH_TOP_50_COINS_FAILURE"

export const FETCH_MARKET_CHART = "FETCH_MARKET_CHART"
export const FETCH_MARKET_CHART_SUCCESS = "FETCH_MARKET_CHART_SUCCESS"
export const FETCH_MARKET_CHART_FAILURE = "FETCH_MARKET_CHART_FAILURE"

export const FETCH_COIN_BY_ID = "FETCH_COIN_BY_ID"
export const FETCH_COIN_BY_ID_SUCCESS = "FETCH_COIN_BY_ID_SUCCESS"
export const FETCH_COIN_BY_ID_FAILURE = "FETCH_COIN_BY_ID_FAILURE"

export const FETCH_COIN_DETAILS = "FETCH_COIN_DETAILS"
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS"
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE"

export const SEARCH_COIN = "SEARCH_COIN"
export const SEARCH_COIN_SUCCESS = "SEARCH_COIN_SUCCESS"
export const SEARCH_COIN_FAILURE = "SEARCH_COIN_FAILURE"